# Introduction to Python - Basic Level

👋 Welcome to my **workspace**. I share my learning and notes.

# Introduction to Python Interactive Cheat Sheet

## Math and variables


In [6]:
# Addition
print(5 + 5)

# Subtraction
print(10 - 5)

# Multiplication
print(5 * 10)

# Division
print(10 / 5)  #float

#Floor Division
print(11//2)  #int

#Modulus
print(10%5)

#Exponentiation
print(2**4)

10
5
50
2.0
5
0
16


Assign values to variables using the `=` sign.

In [25]:
# Assign a value to x
x = 6

# Print x
print(x)

Use the `type()` function to determine the type of a variable.
Notes: str, float, int and bool

In [5]:
# Assign a variable to x
x = "coding"

# Print the type of x
print(type(x))  #string

#More exemples 
x1 = 2.3  
print(type(x1))  #float

x2= 1
print(type(x2)) #int

x3 = True
print(type(x3)) #boolean

<class 'str'>
<class 'float'>
<class 'int'>
<class 'bool'>


To convert the type of a variable, we can use functions such as:
- `str()` to convert to a string.
- `int()` to convert to an integer.
- `float()` to convert to a float.

In [8]:
# Assign a string variable to y
y = "1"

# Print y as an integer
print(int(y))

# Print y as a float
print(float(y))

#More exemples
x= 4
print(str(x))

c2= 2.90
print(int(c2))

1
1.0
4
2


## Lists
To create a list use square brackets `[]`, and use commas to separate the values.

In [10]:
# Create a list
my_list1 = ["Python", "is", "fun!"]

# Print the list
print(my_list1)

['Python', 'is', 'fun!']


To slice multiple values, use `:` to specify the start and stop (not included) of your slice. 

In [19]:
# Create a list
#0-> Python  -3  
#1-> is      -2
#2 -> fun!   -1

my_list = ["Python", "is", "fun!"]

# Print the first element of my_list
print(my_list[0])  

# Print the last element of my_list
print(my_list[-2])

# Print the first two elements of my_list
print(my_list[0:2])

#More exemples
print(my_list[0:1])  #Start in 0 ends in 1 is Python

my_list2 = ['Good','Inspiration','Positive','amazing','nice']
print(my_list2[1:4])

print(my_list2[0:2])

print(my_list2[0:3])


Python
is
['Python', 'is']
['Python']
['Inspiration', 'Positive', 'amazing']
['Good', 'Inspiration', 'Positive']
['Good', 'Inspiration']


It's possible to replace elements of a list by slicing and assigning a new value.

In [1]:
# Create a list
numbers = [1, 2, 3, 4, 5]

# Change the last value
numbers[-1] = 6   #change 5 to 6

# Print the list
print(numbers)

[1, 2, 3, 4, 6]


It's possible to extend a list using `+`.

In [3]:
# Create a list
numbers = [1, 2, 3, 4, 5]

# Add additional values
more_numbers = numbers + [6, 7, 8, 9, 10, 11,12]
more_numbers2 = more_numbers + [13,14,15,16]

# Print the list
print(more_numbers2)

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16]


Use `del()` to delete elements of a list.

In [7]:
# Create a list
numbers = [1, 2, 3, 4, 5]

numbers2 = [6,7,8,9,10,11,12,13]

# Delete the fourth and fifth values in the list
del(numbers[3:])  #delete last 2 elements of a list
del(numbers2[4:]) #delete fourth element until last element

# Print the list
print(numbers)

print(numbers2)


[1, 2, 3]
[6, 7, 8, 9]


## String and list methods
There're a variety of methods we can use on strings, such as capitalization and counting the number of characters. 
(Upper) -> uppercase
(Lower) -> lowercase
(count) -> numbers of a's in this case.

In [8]:
# Define a string variable
x = "data science"

# Convert the string to uppercase
print(x.upper())  # DATA SCIENCE

# Convert the string to lowercase
print(x.lower())  # data science

# Count the number of 'a's
print(x.count("a"))  # 2 a's in DAtA Science

DATA SCIENCE
data science
2


Lists also have a number of methods to assist with calculations, searching for values, and adjusting the list.

In [9]:
# Define a list
colors = ["red", "blue", "red", "red", "blue", "green", "purple"]

# Print out the number of times 'red' appears
print(colors.count("red"))  #count the numbers of red

# Print out the index of the first 'red'
print(colors.index("red"))

# Add another element to the list
colors.append("yellow")  #add yellow in this list
print(colors)

# Reverse the list
colors.reverse()  #reverse the elements of list. Yellow was the last element, but now it's the first element
print(colors)

3
0
['red', 'blue', 'red', 'red', 'blue', 'green', 'purple', 'yellow']
['yellow', 'purple', 'green', 'blue', 'red', 'red', 'blue', 'red']


## NumPy
Import packages like NumPy, by using `import`, followed by the name of the package you want to import. We can use `as` after the package name to specify an alias you can refer to later.

According to https://numpy.org/doc/stable/user/whatisnumpy.htmlIt. NumPy is a Python library which provides a multidimensional array object, for fast operations on array. It is widely used in Data science and Data analytics and it's 50x faster than Python lists.

In [1]:

# Import numpy
import numpy as np

# Assign the names to a list
names = np.array(['Kiko Calero', 'Armando Benitez', 'Delmon Young', 'Greg Maddux', 'J.D. Drew', 'James Loney', 'Jeff Ridgway', 'Ronny Cedeno', 'Omar Infante', 'Wandy Rodriguez'])

# Assign the positions to a list
positions = np.array(['Pitcher', 'Pitcher', 'Outfielder', 'Pitcher', 'Outfielder', 'Infielder', 'Pitcher', 'Infielder', 'Infielder', 'Pitcher'])

# Assign the heights to a list
heights = np.array([73, 76, 75, 72, 73, 75, 75, 72, 72, 71])

# Print the mean height of the players
print(np.mean(heights))

73.4


 Numpay array facilitates advanced mathematical and other types of operations on large numbers of data. An `ndarray` is a (usually fixed-size) multidimensional container of items of the same type and size. 
 
The number of dimensions is the rank of the array. Also the shape of an array is a tuple of integers giving the size of the array along each dimension.

Create a NumPy array from a list using `np.array()`.

In [11]:
# Import NumPy as np
import numpy as np

In [14]:
# Create a list
numbers = [1, 2, 3, 4, 5, 6, 7]

# Convert the list to an array
numbers_array = np.array(numbers)

# Print the type of numbers_array
print(type(numbers))  #list
print(type(numbers_array))  #numpy.ndarray

<class 'list'>
<class 'numpy.ndarray'>


You can perform mathematical operations on a NumPy array as you would with a value.

In [37]:
# Create an array
numbers = np.array([1, 2, 3, 4, 5])

# Multiply the array by 10
numbers_multiplied = numbers * 10

# Print the array
print(numbers_multiplied)

We can subset an array in the same way you would with a list, using square brackets `[]` and colons `:`.

In [15]:
# Create an array
sales = np.array([110, 260, 50, 390, 30])

# Subset the array
first_sales = sales[0:2]

# Print the subset
print(first_sales)

[110 260]


We can also use operators such as `<` and `>` to create a Boolean NumPy array. We can then use the Boolean array to subset your original array.

In [19]:
# Create an array
sales = np.array([110, 260, 50, 390, 30, 40, 70])
costs = np.array([900, 1000, 5000, 600, 8000, 9000])

# Create a Boolean array
large_sales = sales > 100   # only numbers greater than 100
large_costs = numbers3 >= 1000   # only numbers greater than or equal to 1000

# Subset the original array
print(sales[large_sales])
print(costs[large_costs])

[110 260 390]
[1000 5000 8000 9000]


We can create a 2D NumPy array by creating a list of lists, and then converting it to an array using `np.array()`.

In [40]:
# Create a list of lists
sales = [[1, 110],
         [2, 260],
         [3, 50]
        ]

# Convert the list to a NumPy array
sales_array = np.array(sales)

# Print the array
print(sales_array)

To subset a 2D NumPy array, we use square brackets `[]`, but specify both the row and column index, separated by a comma (`,`).

In [28]:
# Create a list of lists
monthly_sales = [[1, 190],
         [2, 210],
         [3, 185]
        ]

# Convert the list to a NumPy array
sales = np.array(monthly_sales)

# Print 
print(monthly_sales)

[[1, 190], [2, 210], [3, 185]]


We can use functions such as `np.mean()`, `np.median()`, and `np.std()` to generate summary statistics of NumPy arrays.

In [29]:
# Create a NumPy array of sales
sales = np.array([190, 210, 185, 235, 170, 270, 240, 225, 260])

# Calculate the average
print(np.mean(sales))   # mean

# Calculate the median
print(np.median(sales))  # median

# Calculate the standard deviation
print(np.std(sales))

220.55555555555554
225.0
32.44178071256985


We can also use `np.corrcoef()` to calculate the correlation between two NumPy arrays.

In [41]:
import numpy as np

# Create a NumPy array of sales
array1 = np.array([0, 1, 2, 3 ,4]) 

# Create a NumPy array of marketing expenses
array2 = np.array([5, 6, 7, 8, 9])

# Calculate the correlation between the two arrays
result = np.corrcoef(array1,array2)

print(result)

[[1. 1.]
 [1. 1.]]
